# Generated by Django 5.0.6 on 2024-09-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='orderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.orderitem'),
        ),
    ]
