# Generated by Django 5.0.6 on 2024-09-23 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_orderitem_order_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderitem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='food.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
